CREATE TABLE `Anagrafica` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Nomeaccount` text,
  `SFRegion` text,
  `SFDistrict` text,
  `SFTerritory` text,
  `Tipodirecordaccount` text,
  `RRPSegment` text,
  `Trade` text,
  `CAPspedizioni` text,
  `StatoProvinciaspedizioni` text,
  `Cittspedizioni` text,
  `Indirizzospedizioni` text,
  `Telefono` text,
  `Mobile` text,
  `Email` text,
  `FieldRep` text,
  `NumeroFieldRep` text,
  `Supervisor` text,
  `NumeroSupervisor` text,
  PRIMARY KEY (`id`),
  KEY `Nomeaccount` (`Nomeaccount`(255))
) ENGINE=InnoDB AUTO_INCREMENT=59585 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ClusterDONE` (
  `id` int NOT NULL AUTO_INCREMENT,
  `TERRITORIO` text,
  `RRPSEGMENT` text,
  `STATUS` text,
  `POS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COSTUMERID` text,
  `SRDR` text,
  `CEL` text,
  `ADDRESS` text,
  `PROV` text,
  `CAP` text,
  `INSTALLER` text,
  `FIXTURE` text,
  `CODFIXTURE` text,
  `FLOORWALL` text,
  `RIPIANI` text,
  `DISPOSIZONEMODULI` text,
  `NOTEALCODICE` text,
  `FA` text,
  `PO` text,
  `CODVISIBILITYBOX` text,
  `CODSTRUMENTOVISIBILITAN1` text,
  `CODSTRUMENTOVISIBILITAN2` text,
  `GTKA` text,
  `DATASOPRALLUOGO` text,
  `SUPERVISORREPRESENTE` text,
  `DDT` text,
  `DATAINSTALLoRITIROoMANUT` text,
  `ATTIVITAEFFETTUATA` text,
  `DATAPROSSIMAATTIVITA` text,
  `ORAPROSSIMAATTIVITA` text,
  `NOTEPM` text,
  `NOTEROL` text,
  `MODULO60` text,
  `MODULO90` text,
  `VISIBILITY60` text,
  `VISIBILITY90` text,
  `LIGHTBOX60` text,
  `LIGHTBOX90` text,
  `MONITOR90` text,
  `MONITOR60` text,
  `FIANCO` text,
  `LB_LOGOFRES` text,
  `PROLUNGAMENTO` text,
  `MODULOILUMA` text,
  `CARDS` text,
  `PUSHER` text,
  `LIGHTTOTEM` text,
  `WALLTOTEM60` text,
  `WALLTOTEM90` text,
  `COSTO` text,
  `EXTRANONLAVORATIVO` text,
  `ALTRIEXTRA` text,
  `Column` text,
  `TECNICO` text,
  `Column_1` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8342 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `g_anagrafica` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome_account` varchar(255) DEFAULT NULL,
  `sf_region` varchar(255) DEFAULT NULL,
  `sf_district` varchar(255) DEFAULT NULL,
  `sf_territory` varchar(255) DEFAULT NULL,
  `tipo_di_record_account` varchar(255) DEFAULT NULL,
  `rrp_segment` varchar(255) DEFAULT NULL,
  `trade` varchar(255) DEFAULT NULL,
  `cap_spedizioni` varchar(255) DEFAULT NULL,
  `statoprovincia_spedizioni` varchar(255) DEFAULT NULL,
  `citt_spedizioni` varchar(255) DEFAULT NULL,
  `indirizzo_spedizioni` varchar(255) DEFAULT NULL,
  `telefono` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `field_rep` varchar(255) DEFAULT NULL,
  `numero_field_rep` varchar(255) DEFAULT NULL,
  `supervisor` varchar(255) DEFAULT NULL,
  `numero_supervisor` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=59585 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `g_cluster_20250113` (
  `id` int NOT NULL AUTO_INCREMENT,
  `territorio` varchar(255) DEFAULT NULL,
  `rrp_segment` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `pos` varchar(255) DEFAULT NULL,
  `costumer_id` varchar(255) DEFAULT NULL,
  `srdr` varchar(255) DEFAULT NULL,
  `cel` varchar(255) DEFAULT NULL,
  `indirizzo` varchar(255) DEFAULT NULL,
  `prov` varchar(255) DEFAULT NULL,
  `cap` varchar(255) DEFAULT NULL,
  `installer` varchar(255) DEFAULT NULL,
  `fixture` varchar(255) DEFAULT NULL,
  `codfixture` varchar(255) DEFAULT NULL,
  `floor_wall` varchar(255) DEFAULT NULL,
  `ripiani` varchar(255) DEFAULT NULL,
  `disposizione_moduli` varchar(255) DEFAULT NULL,
  `note_al_codice` varchar(255) DEFAULT NULL,
  `fa` varchar(255) DEFAULT NULL,
  `pa` varchar(255) DEFAULT NULL,
  `cod_visibility_box_sign` varchar(255) DEFAULT NULL,
  `cod_strumento_di_visibilita_n1_interno` varchar(255) DEFAULT NULL,
  `cod_strumento_di_visibilita_n2_window` varchar(255) DEFAULT NULL,
  `gtka` varchar(255) DEFAULT NULL,
  `data_sopralluogo` varchar(255) DEFAULT NULL,
  `supervisorre_presente` varchar(255) DEFAULT NULL,
  `numero_picking` varchar(255) DEFAULT NULL,
  `data_install_o_ritiro_o_manut` varchar(255) DEFAULT NULL,
  `prossima_attivita` varchar(255) DEFAULT NULL,
  `data_prossima_attivita` varchar(255) DEFAULT NULL,
  `ora_prossima_attivita` varchar(255) DEFAULT NULL,
  `note_pm` varchar(255) DEFAULT NULL,
  `note_rol` varchar(255) DEFAULT NULL,
  `modulo_60` varchar(255) DEFAULT NULL,
  `modulo_90` varchar(255) DEFAULT NULL,
  `visibility_60` varchar(255) DEFAULT NULL,
  `visibility_90` varchar(255) DEFAULT NULL,
  `lightbox_60` varchar(255) DEFAULT NULL,
  `lightbox_90` varchar(255) DEFAULT NULL,
  `monitor_90` varchar(255) DEFAULT NULL,
  `monitor_60` varchar(255) DEFAULT NULL,
  `fianco_f` varchar(255) DEFAULT NULL,
  `lb_logo_fres` varchar(255) DEFAULT NULL,
  `prolungamento` varchar(255) DEFAULT NULL,
  `modulo_iluma` varchar(255) DEFAULT NULL,
  `cards` varchar(255) DEFAULT NULL,
  `pusher` varchar(255) DEFAULT NULL,
  `light_totem` varchar(255) DEFAULT NULL,
  `wall_totem_60` varchar(255) DEFAULT NULL,
  `wall_totem_90` varchar(255) DEFAULT NULL,
  `costo` varchar(255) DEFAULT NULL,
  `extra_non_lavorativo` varchar(255) DEFAULT NULL,
  `altri_extra` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1085 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `g_pos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `area` varchar(255) DEFAULT NULL,
  `distretto` varchar(255) DEFAULT NULL,
  `territorio` varchar(255) DEFAULT NULL,
  `nome_pos` varchar(255) DEFAULT NULL,
  `prov` varchar(255) DEFAULT NULL,
  `rrp_segment` varchar(255) DEFAULT NULL,
  `status_pos` varchar(255) DEFAULT NULL,
  `commenti` varchar(255) DEFAULT NULL,
  `data_inserimento_pos` varchar(255) DEFAULT NULL,
  `presa_in_cariconon_presa_in_carico` varchar(255) DEFAULT NULL,
  `motivo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=537 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `phonetest` (
  `id` int NOT NULL,
  `nome` varchar(100) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `note` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `route_optimizer_plans` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `plan_data` json NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_name` (`name`),
  CONSTRAINT `fk_route_plans_user` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `t_camp_auto_responses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `trigger_pattern` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `response_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_regex` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `priority` int NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_priority_active` (`priority`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_camp_campaigns` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `target_table` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `message_template` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('draft','active','paused','completed','failed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `total_recipients` int NOT NULL DEFAULT '0',
  `sent_count` int NOT NULL DEFAULT '0',
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `t_camp_campaigns_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=94 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_camp_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `campaign_id` int DEFAULT NULL,
  `action_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `user_id` (`user_id`),
  KEY `idx_action_type` (`action_type`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `t_camp_logs_ibfk_1` FOREIGN KEY (`campaign_id`) REFERENCES `t_camp_campaigns` (`id`) ON DELETE SET NULL,
  CONSTRAINT `t_camp_logs_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_camp_messages` (
  `id` int NOT NULL AUTO_INCREMENT,
  `campaign_id` int NOT NULL,
  `recipient_id` int DEFAULT NULL,
  `sender_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ultramsg_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Contenuto del messaggio o caption per media',
  `raw_data` json DEFAULT NULL,
  `status` enum('sent','delivered','read','failed','received') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sent',
  `direction` enum('inbound','outbound') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'outbound',
  `error_message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `data_msg` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `media_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Tipo di media (image, document, video, audio, etc.)',
  `media_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL del media da UltraMsg',
  `media_filename` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Nome originale del file',
  `media_caption` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Didascalia del media',
  `media_mimetype` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MIME type del media',
  `media_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Path locale del file media',
  `media_size` bigint DEFAULT NULL COMMENT 'Dimensione del file in bytes',
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `recipient_id` (`recipient_id`),
  KEY `idx_ultramsg_id` (`ultramsg_id`),
  KEY `idx_status` (`status`),
  KEY `idx_media_type` (`media_type`),
  KEY `idx_media_url` (`media_url`(255)),
  CONSTRAINT `t_camp_messages_ibfk_1` FOREIGN KEY (`campaign_id`) REFERENCES `t_camp_campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `t_camp_messages_ibfk_2` FOREIGN KEY (`recipient_id`) REFERENCES `t_camp_recipients` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_camp_recipients` (
  `id` int NOT NULL AUTO_INCREMENT,
  `campaign_id` int NOT NULL,
  `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `custom_data` json DEFAULT NULL,
  `status` enum('pending','sent','failed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `sent_at` timestamp NULL DEFAULT NULL,
  `error_message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `idx_phone` (`phone`),
  KEY `idx_status` (`status`),
  CONSTRAINT `t_camp_recipients_ibfk_1` FOREIGN KEY (`campaign_id`) REFERENCES `t_camp_campaigns` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11323 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_contacts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_message_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_phone` (`phone`),
  KEY `idx_last_message` (`last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_files` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pos_id` int NOT NULL,
  `user_id` varchar(50) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `filepath` varchar(255) NOT NULL,
  `description` text,
  `upload_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `pos_id` (`pos_id`),
  CONSTRAINT `t_files_ibfk_1` FOREIGN KEY (`pos_id`) REFERENCES `Anagrafica` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `t_groups` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_menu_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `page_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_id` int DEFAULT NULL,
  `menu_type` enum('main','sidebar','config') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `menu_order` int DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_menu_items_parent` (`parent_id`),
  CONSTRAINT `t_menu_items_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `t_menu_items` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_menu_permissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `group_id` int DEFAULT NULL,
  `menu_id` int DEFAULT NULL,
  `can_view` tinyint(1) DEFAULT '0',
  `can_edit` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_permissions_group` (`group_id`),
  KEY `idx_permissions_menu_item` (`menu_id`),
  CONSTRAINT `t_menu_permissions_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `t_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `t_menu_permissions_ibfk_2` FOREIGN KEY (`menu_id`) REFERENCES `t_menu_items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `message` varchar(255) NOT NULL,
  `is_read` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `t_notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `t_reports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `table_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `sql_query` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `query_prompt` text COLLATE utf8mb4_unicode_ci,
  `can_read` tinyint(1) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `table_name` (`table_name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `table_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `group_id` int NOT NULL DEFAULT '1',
  `can_read` tinyint(1) DEFAULT '1',
  `can_write` tinyint(1) DEFAULT '1',
  `can_delete` tinyint(1) DEFAULT '1',
  `import_type` enum('raw','db') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `table_name` (`table_name`),
  KEY `idx_group_id` (`group_id`),
  KEY `idx_table_name` (`table_name`)
) ENGINE=InnoDB AUTO_INCREMENT=26417 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_table_perm` (
  `id` int NOT NULL AUTO_INCREMENT,
  `table_name` varchar(100) NOT NULL,
  `description` varchar(255) NOT NULL,
  `group_id` int NOT NULL,
  `perm_level` int NOT NULL,
  `active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_table_group_perm` (`table_name`,`group_id`,`perm_level`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `t_user_groups` (
  `user_id` int NOT NULL,
  `group_id` int NOT NULL,
  PRIMARY KEY (`user_id`,`group_id`),
  KEY `group_id` (`group_id`),
  CONSTRAINT `t_user_groups_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `t_user_groups_ibfk_2` FOREIGN KEY (`group_id`) REFERENCES `t_groups` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `t_users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `last_login` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_users_username` (`username`),
  KEY `idx_users_email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=772 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tsis_anagrafica` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome_account` varchar(255) DEFAULT NULL,
  `sf_region` varchar(255) DEFAULT NULL,
  `sf_district` varchar(255) DEFAULT NULL,
  `sf_territory` varchar(255) DEFAULT NULL,
  `tipo_di_record_account` varchar(255) DEFAULT NULL,
  `rrp_segment` varchar(255) DEFAULT NULL,
  `trade` varchar(255) DEFAULT NULL,
  `cap_spedizioni` varchar(255) DEFAULT NULL,
  `statoprovincia_spedizioni` varchar(255) DEFAULT NULL,
  `citt_spedizioni` varchar(255) DEFAULT NULL,
  `indirizzo_spedizioni` varchar(255) DEFAULT NULL,
  `telefono` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `field_rep` varchar(255) DEFAULT NULL,
  `numero_field_rep` varchar(255) DEFAULT NULL,
  `supervisor` varchar(255) DEFAULT NULL,
  `numero_supervisor` varchar(255) DEFAULT NULL,
  `tree_data` json DEFAULT NULL,
  `tree_updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_nome_account` (`nome_account`),
  KEY `idx_region` (`sf_region`),
  KEY `idx_district` (`sf_district`),
  KEY `idx_territory` (`sf_territory`),
  KEY `idx_rrp_segment` (`rrp_segment`)
) ENGINE=InnoDB AUTO_INCREMENT=238351 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_attivita_ordine_pos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `codice` varchar(50) NOT NULL,
  `descrizione` text,
  `template_data` json DEFAULT NULL,
  `attivo` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `data_creazione` datetime DEFAULT CURRENT_TIMESTAMP,
  `utente_creazione` int DEFAULT NULL,
  `data_modifica` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `utente_modifica` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `codice` (`codice`),
  KEY `utente_creazione` (`utente_creazione`),
  KEY `utente_modifica` (`utente_modifica`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `tsis_attivita_ordine_pos_ibfk_1` FOREIGN KEY (`utente_creazione`) REFERENCES `t_users` (`id`),
  CONSTRAINT `tsis_attivita_ordine_pos_ibfk_2` FOREIGN KEY (`utente_modifica`) REFERENCES `t_users` (`id`),
  CONSTRAINT `tsis_attivita_ordine_pos_ibfk_3` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_geocode_cache` (
  `id` int NOT NULL AUTO_INCREMENT,
  `address` varchar(255) NOT NULL,
  `lat` float(10,6) NOT NULL,
  `lng` float(10,6) NOT NULL,
  `formatted_address` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `address` (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Picking list name',
  `description` text COMMENT 'Picking list description',
  `status` enum('draft','confirmed','ordered','partially_received','completed','cancelled') NOT NULL DEFAULT 'draft',
  `order_date` date DEFAULT NULL COMMENT 'Date when the order was placed',
  `expected_delivery_date` date DEFAULT NULL COMMENT 'Expected delivery date',
  `delivery_address` text COMMENT 'Delivery address',
  `notes` text COMMENT 'Additional notes',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pick_list_status` (`status`),
  KEY `idx_pick_list_created_by` (`created_by`),
  KEY `idx_pick_list_updated_by` (`updated_by`),
  CONSTRAINT `fk_pick_list_created_by` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `fk_pick_list_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_list_detail` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pick_list_id` int NOT NULL COMMENT 'Reference to pick list',
  `supplier_id` int DEFAULT NULL COMMENT 'Reference to supplier',
  `material_id` int DEFAULT NULL COMMENT 'Reference to material (NULL if custom)',
  `is_custom` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this is a custom material',
  `article_code` varchar(100) DEFAULT NULL COMMENT 'Material article code',
  `description` varchar(255) NOT NULL COMMENT 'Material description',
  `quantity` decimal(10,2) NOT NULL COMMENT 'Required quantity',
  `unit_of_measure` varchar(10) NOT NULL DEFAULT 'PZ' COMMENT 'Unit of measure',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT 'Unit price',
  `total_price` decimal(12,2) GENERATED ALWAYS AS ((`quantity` * `unit_price`)) STORED COMMENT 'Total price',
  `ordered_quantity` decimal(10,2) DEFAULT NULL COMMENT 'Actually ordered quantity',
  `received_quantity` decimal(10,2) DEFAULT NULL COMMENT 'Received quantity',
  `notes` text COMMENT 'Additional notes',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pick_detail_list` (`pick_list_id`),
  KEY `idx_pick_detail_supplier` (`supplier_id`),
  KEY `idx_pick_detail_material` (`material_id`),
  CONSTRAINT `fk_pick_detail_list` FOREIGN KEY (`pick_list_id`) REFERENCES `tsis_pick_list` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pick_detail_material` FOREIGN KEY (`material_id`) REFERENCES `tsis_pick_material` (`id`),
  CONSTRAINT `fk_pick_detail_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `tsis_pick_supplier` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=280 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_material` (
  `id` int NOT NULL AUTO_INCREMENT,
  `supplier_id` int NOT NULL COMMENT 'Reference to supplier',
  `article_code` varchar(100) NOT NULL COMMENT 'Material article code',
  `description` varchar(255) NOT NULL COMMENT 'Material description',
  `unit_of_measure` varchar(10) NOT NULL DEFAULT 'PZ' COMMENT 'Unit of measure (PZ, M, KG, etc.)',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT 'Unit price',
  `category` varchar(50) DEFAULT NULL COMMENT 'Material category',
  `subcategory` varchar(50) DEFAULT NULL COMMENT 'Material subcategory',
  `notes` text COMMENT 'Additional notes',
  `active` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether the material is active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_supplier_article` (`supplier_id`,`article_code`),
  KEY `idx_material_active` (`active`),
  KEY `idx_material_category` (`category`),
  KEY `idx_material_created_by` (`created_by`),
  KEY `idx_material_updated_by` (`updated_by`),
  CONSTRAINT `fk_material_created_by` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `fk_material_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=298 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_module` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL COMMENT 'Module code (e.g. FLEXTER600)',
  `name` varchar(255) NOT NULL COMMENT 'Module display name',
  `width` int NOT NULL COMMENT 'Module width in mm',
  `height` int NOT NULL COMMENT 'Module height in mm',
  `depth` int NOT NULL COMMENT 'Module depth in mm',
  `installation_type` enum('FLOOR','WALL','BOTH') NOT NULL DEFAULT 'BOTH' COMMENT 'Allowed installation type',
  `description` text COMMENT 'Module description',
  `active` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether the module is active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_module_code` (`code`),
  KEY `idx_module_active` (`active`),
  KEY `idx_module_created_by` (`created_by`),
  KEY `idx_module_updated_by` (`updated_by`),
  CONSTRAINT `fk_module_created_by` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `fk_module_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_module_material` (
  `id` int NOT NULL AUTO_INCREMENT,
  `module_id` int NOT NULL COMMENT 'Reference to module',
  `material_id` int NOT NULL COMMENT 'Reference to material',
  `quantity` decimal(10,2) NOT NULL DEFAULT '1.00' COMMENT 'Required quantity of material for this module',
  `mandatory` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether the material is mandatory for the module',
  `installation_type` enum('FLOOR','WALL','BOTH') NOT NULL DEFAULT 'BOTH' COMMENT 'Installation type this material is needed for',
  `notes` text COMMENT 'Additional notes',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_module_material` (`module_id`,`material_id`,`installation_type`),
  KEY `fk_mm_material_id` (`material_id`),
  CONSTRAINT `fk_mm_material_id` FOREIGN KEY (`material_id`) REFERENCES `tsis_pick_material` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_mm_module_id` FOREIGN KEY (`module_id`) REFERENCES `tsis_pick_module` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_pos_custom_material` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pos_order_id` int NOT NULL COMMENT 'Reference to order in tsis_pos_management',
  `supplier_id` int DEFAULT NULL COMMENT 'Reference to supplier (optional)',
  `article_code` varchar(100) DEFAULT NULL COMMENT 'Material article code (optional)',
  `description` varchar(255) NOT NULL COMMENT 'Material description',
  `quantity` decimal(10,2) NOT NULL DEFAULT '1.00' COMMENT 'Required quantity',
  `unit_of_measure` varchar(10) NOT NULL DEFAULT 'PZ' COMMENT 'Unit of measure',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT 'Unit price',
  `notes` text COMMENT 'Additional notes',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_poscustom_order` (`pos_order_id`),
  KEY `idx_poscustom_supplier` (`supplier_id`),
  KEY `idx_poscustom_created_by` (`created_by`),
  KEY `idx_poscustom_updated_by` (`updated_by`),
  CONSTRAINT `fk_poscustom_created_by` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `fk_poscustom_order` FOREIGN KEY (`pos_order_id`) REFERENCES `tsis_pos_management` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_poscustom_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `tsis_pick_supplier` (`id`),
  CONSTRAINT `fk_poscustom_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_pos_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pick_list_id` int NOT NULL COMMENT 'Reference to pick list',
  `pos_order_id` int NOT NULL COMMENT 'Reference to order in tsis_pos_management',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_picklist_pos` (`pick_list_id`,`pos_order_id`),
  KEY `idx_pick_pos_order` (`pos_order_id`),
  CONSTRAINT `fk_pick_pos_list` FOREIGN KEY (`pick_list_id`) REFERENCES `tsis_pick_list` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pick_pos_order` FOREIGN KEY (`pos_order_id`) REFERENCES `tsis_pos_management` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_pos_module` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pos_order_id` int NOT NULL COMMENT 'Reference to order in tsis_pos_management',
  `module_id` int NOT NULL COMMENT 'Reference to module',
  `quantity` int NOT NULL DEFAULT '1' COMMENT 'Number of modules to install',
  `installation_type` enum('FLOOR','WALL') NOT NULL COMMENT 'Installation type (FLOOR/WALL)',
  `position` varchar(100) DEFAULT NULL COMMENT 'Position description within the POS',
  `notes` text COMMENT 'Additional notes',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_posmodule_order` (`pos_order_id`),
  KEY `idx_posmodule_module` (`module_id`),
  KEY `idx_posmodule_created_by` (`created_by`),
  KEY `idx_posmodule_updated_by` (`updated_by`),
  CONSTRAINT `fk_posmodule_created_by` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `fk_posmodule_module` FOREIGN KEY (`module_id`) REFERENCES `tsis_pick_module` (`id`),
  CONSTRAINT `fk_posmodule_order` FOREIGN KEY (`pos_order_id`) REFERENCES `tsis_pos_management` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_posmodule_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pick_supplier` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Supplier name',
  `code` varchar(50) NOT NULL COMMENT 'Supplier code',
  `contact_person` varchar(255) DEFAULT NULL COMMENT 'Contact person at supplier',
  `email` varchar(255) DEFAULT NULL COMMENT 'Supplier email',
  `phone` varchar(50) DEFAULT NULL COMMENT 'Supplier phone',
  `address` text COMMENT 'Supplier address',
  `active` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether the supplier is active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_supplier_code` (`code`),
  KEY `idx_supplier_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pm_config` (
  `user_id` int NOT NULL,
  `area_competenza` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `max_pos_assegnabili` int DEFAULT '50',
  `note` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `tsis_pm_config_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tsis_pos_imports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome_documento` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nome_file_salvato` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `percorso_file` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importato_da` int NOT NULL,
  `numero_pos` int DEFAULT '0',
  `stato` enum('nuovo','in_corso','completato','completato_con_errori','errore') COLLATE utf8mb4_unicode_ci DEFAULT 'nuovo',
  `note_importazione` text COLLATE utf8mb4_unicode_ci,
  `data_inizio` datetime DEFAULT NULL,
  `data_creazione` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `data_completamento` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tsis_pos_imports_ibfk_1` (`importato_da`),
  CONSTRAINT `tsis_pos_imports_ibfk_1` FOREIGN KEY (`importato_da`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tsis_pos_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `pos_id` bigint NOT NULL,
  `tipo_operazione` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dati_precedenti` text COLLATE utf8mb4_unicode_ci,
  `motivo_operazione` text COLLATE utf8mb4_unicode_ci,
  `utente_id` bigint DEFAULT NULL,
  `data_operazione` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_id` (`pos_id`),
  KEY `idx_utente_id` (`utente_id`),
  KEY `idx_data_operazione` (`data_operazione`)
) ENGINE=InnoDB AUTO_INCREMENT=1669 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tsis_pos_management` (
  `id` int NOT NULL AUTO_INCREMENT,
  `import_id` int NOT NULL,
  `pos_id` int NOT NULL,
  `pm_id` int DEFAULT NULL,
  `stato` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `motivo_standby` text COLLATE utf8mb4_unicode_ci,
  `motivo_chiusura` text COLLATE utf8mb4_unicode_ci,
  `commenti_cliente` text COLLATE utf8mb4_unicode_ci,
  `commenti_interni` text COLLATE utf8mb4_unicode_ci,
  `data_assegnazione` datetime DEFAULT NULL,
  `data_inizio_lavorazione` datetime DEFAULT NULL,
  `data_ultimo_stato` datetime DEFAULT NULL,
  `data_creazione` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `data_modifica` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `tipo_attivita_id` int DEFAULT NULL,
  `data_ordine` date DEFAULT NULL,
  `codice_ordine` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codice_po_fornitore` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tasks_data` json DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `id_stato` int DEFAULT NULL,
  `progress` int DEFAULT '0',
  `version` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_stato` (`stato`),
  KEY `idx_pos_pm` (`pm_id`),
  KEY `idx_pos_date` (`data_assegnazione`,`data_ultimo_stato`),
  KEY `idx_codice_po_fornitore` (`codice_po_fornitore`),
  KEY `tsis_pos_management_ibfk_1` (`import_id`),
  KEY `fk_tipo_attivita` (`tipo_attivita_id`),
  KEY `fk_updated_by` (`updated_by`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `fk_stato_avanzamento` (`id_stato`),
  CONSTRAINT `fk_pm_user` FOREIGN KEY (`pm_id`) REFERENCES `t_users` (`id`),
  CONSTRAINT `fk_pos_management_stato` FOREIGN KEY (`id_stato`) REFERENCES `tsis_stati_avanzamento` (`id`),
  CONSTRAINT `fk_stato_avanzamento` FOREIGN KEY (`id_stato`) REFERENCES `tsis_stati_avanzamento` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tipo_attivita` FOREIGN KEY (`tipo_attivita_id`) REFERENCES `tsis_attivita_ordine_pos` (`id`),
  CONSTRAINT `fk_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `tsis_pos_management_ibfk_1` FOREIGN KEY (`import_id`) REFERENCES `tsis_pos_imports` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2741 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tsis_pos_management_pm_backup` (
  `id` int NOT NULL DEFAULT '0',
  `pm_id` int DEFAULT NULL,
  `data_assegnazione` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_pos_task_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `tipo_attivita_id` int NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `template_data` json NOT NULL,
  `created_by` int NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tipo_attivita_id` (`tipo_attivita_id`),
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `tsis_pos_task_templates_ibfk_1` FOREIGN KEY (`tipo_attivita_id`) REFERENCES `tsis_attivita_ordine_pos` (`id`),
  CONSTRAINT `tsis_pos_task_templates_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `t_users` (`id`),
  CONSTRAINT `tsis_pos_task_templates_ibfk_3` FOREIGN KEY (`updated_by`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tsis_route_optimizations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `optimization_date` datetime NOT NULL,
  `start_point` varchar(255) NOT NULL,
  `total_stops` int NOT NULL DEFAULT '0',
  `total_distance_km` float NOT NULL DEFAULT '0',
  `total_time_minutes` float NOT NULL DEFAULT '0',
  `route_data` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_date` (`optimization_date`),
  CONSTRAINT `fk_route_opt_user` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_route_pos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `route_id` int NOT NULL,
  `pos_id` int NOT NULL,
  `visit_duration` int NOT NULL DEFAULT '30',
  `priority` enum('high','normal','low') DEFAULT 'normal',
  `stop_order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_route_pos` (`route_id`,`pos_id`),
  CONSTRAINT `fk_route_pos_route` FOREIGN KEY (`route_id`) REFERENCES `tsis_saved_routes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_saved_routes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text,
  `user_id` int NOT NULL,
  `total_stops` int NOT NULL DEFAULT '0',
  `total_distance_km` float NOT NULL DEFAULT '0',
  `total_time_minutes` float NOT NULL DEFAULT '0',
  `route_data` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_template` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_route_user` (`user_id`),
  CONSTRAINT `fk_saved_route_user` FOREIGN KEY (`user_id`) REFERENCES `t_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tsis_stati_avanzamento` (
  `id` int NOT NULL AUTO_INCREMENT,
  `codice` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `descrizione` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` enum('ordine','task','subtask') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ordine` int NOT NULL DEFAULT '0',
  `colore` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icona` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attivo` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_codice_tipo` (`codice`,`tipo`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `w_rol_accessories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `category` enum('VISIBILITY','LIGHTBOX','MONITOR','EXTENSION') NOT NULL,
  `compatible_width` varchar(50) DEFAULT 'all',
  `active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_accessory_active` (`active`),
  KEY `idx_accessory_category` (`category`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `w_rol_configurations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` enum('draft','active','archived') DEFAULT 'draft',
  PRIMARY KEY (`id`),
  KEY `idx_config_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `w_rol_module_accessories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `module_id` int DEFAULT NULL,
  `accessory_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `accessory_id` (`accessory_id`),
  KEY `idx_module_accessories` (`module_id`,`accessory_id`),
  CONSTRAINT `w_rol_module_accessories_ibfk_1` FOREIGN KEY (`module_id`) REFERENCES `w_rol_modules` (`id`) ON DELETE CASCADE,
  CONSTRAINT `w_rol_module_accessories_ibfk_2` FOREIGN KEY (`accessory_id`) REFERENCES `w_rol_accessories` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `w_rol_modules` (
  `id` int NOT NULL AUTO_INCREMENT,
  `configuration_id` int DEFAULT NULL,
  `module_type` varchar(50) NOT NULL,
  `position` int NOT NULL,
  `shelves_count` int DEFAULT '7',
  PRIMARY KEY (`id`),
  KEY `idx_module_config` (`configuration_id`),
  KEY `idx_module_type` (`module_type`),
  CONSTRAINT `w_rol_modules_ibfk_1` FOREIGN KEY (`configuration_id`) REFERENCES `w_rol_configurations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
